### ISSUE TITLE
Чекбокс «чужой компьютер/не запоминать меня»

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#17]

**Comment by dair** [comment]
А вот эта инверсная логика — оно надо вообще?

**Comment by leotsarev** [comment]
Это можно долго и прочно дискутировать когда-нибудь потом. В версии 0.1 мы всегда запоминаем навсегда или на очень долго. Дальше разберемся, как это делать (и надо ли вообще).
milestone=future для таких задач (на которые мы сейчас точно не будем тратить время).
