### ISSUE TITLE
Нормальная стартовая страница (игроцкая)

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#21]
Копирую из обсуждения:
Если ты зашёл на главную со стороны - то у тебя есть список своих заявок, с пометками, где есть обновления, и список актуальных проектов ниже, с кнопочкой "заявиться". Критерий актуальности нужно будет выписать позже - самый простой это количество принятых заявок за последнюю неделю. И возле твоего ника есть маленькая кнопочка "мои проекты", которая ведёт на master.joinrpg.ru. А если у тебя нет ни одного проекта - то кнопочка "создать проект", ведущая туда же.

Необходимо понаделать здесь мудрых указаний, как должна выглядеть стартовая страница игрока.

**Comment by tsareva** [comment]
Честно говоря, имхо как правило:
Я захожу на аллрпг как мастер с заглавной страницы сайта.
Я захожу на аллрпг как игрок с ссылки уведомления

Во втором случае не принципиально, что часть заглавной страницы занята под Проекты, которыми я как игрок не пользуюсь.
В первом случае очень бесит, что необходим дополнительный клик. Особенно в том разрезе, что у самых активных мастеров (по логике заходят чаще всего) обычно актуальный проект один.

**Comment by dair** [comment]
1. Отдельный домен третьего уровня — зло.
2. Предлагаю интерфейсно, после логина:

2.1. Если у залогиненного есть свои проекты — делить страницу пополам на "мои проекты" и "мои заявки"

2.2. Если есть что-то одно — показывать это что-то одно, чтобы игроки про проекты и не парились. Создавать проекты вообще из какого-то меню и не здесь.

**Comment by leotsarev** [comment]
Согласен с Даиром по (1).

**Comment by Wildmage** [comment]
М-мм, ребята, может, я тогда постою скраю, посмотрю? Если вопросы UX будут решаться a. голосованием, b. до появления пользовательских сценариев, то я не очень понимаю, что я здесь делаю.

**Comment by leotsarev** [comment]
Голосование вроде ничего не решается. Но не понимаю, почему участники проекта не могут высказывать свое мнение. Особенно с учетом того, что высказываются активные живые пользователи системы, а Атана — вообще работала с allrpg.info **каждый день** в течение последних двух лет.

**Comment by Wildmage** [comment]
Лео, это прекрасно. Это значит, что у нас есть уникальный богатый материал для написания пользовательских сценариев.

**Comment by leotsarev** [comment]
Как я уже писал, я с сомнением отношусь к необходимости детального и подробного проектирования, написания многотонных сценариев и прочей писанины. Я верую в agile, вовлечение в разработку пользователей и их представителей, быстрый фидбек и все вот это. 
Понятно, воспретить тебе не могу, и если результатом этого будут хорошие и годные идеи как все правильно сделать, они пойдут в дело.
Вот и этот issue находится сейчас в отложенном состоянии, чтобы ты мог спокойно все сделать. Пока что нужно сделать простую страницу типа #8 чтобы все начало приобретать хоть какой-то живой вид.

**Comment by Wildmage** [comment]
Я в данном случае ничего не говорю о детальном и подробном проектировании программ. Я говорю только о проектировании интерфейсов - это совершенно другая задача. Если сбор опыта пользователей для этих целей не возьмёшься делать ты (или кто-то другой) - это просто значит, что эту работу придётся делать мне, что несколько затянет процесс. Но, как я уже писал, удобные интерфейсы нужны сразу, к самой первой публичной демонстрации проекта.

**Comment by leotsarev** [comment]
Вот тебе типичные сценарии: 
- Мастер заходит на сайт сам (вбивая в адресной строке/закладкой)
- Игрок заходит на сайт либо по прямой ссылке из группы ВК/сайта
- либо с уведомления.

**Comment by giuliorm** [comment]
> > Если у залогиненного есть свои проекты — делить страницу пополам на "мои проекты" и "мои заявки"

+1. Только у пользователя, у которого проектов нет, может быть на одной  "стороне" кнопочка "создать/добавить".
И должны быть где-то ссылки на профиль/настройки профиля/другие страницы подобного рода
