### ISSUE TITLE
Изучение вопроса с форматом ричтекста

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#22]
Друзья, давайте обсудим формат ричтекста в проекте. Варианты, которые приходят в голову:
-  HTML
- Markdown (это как здесь).

Визуальный редактор нужно делать в любом случае, но они вроде есть.
Кто-то может изучить вопрос по редакторам/библиотекам по тому и тому?

@joinrpg/developers @joinrpg/product

**Comment by Wildmage** [comment]
Я сейчас как раз пилю кое-что на тему в качестве домашнего проекта, надеюсь, что через месяц у меня будет, что предложить по теме.
