### ISSUE TITLE
Поля-ссылки на персонажа

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#28]
Необходимо обдумать функционал ссылок одного персонажа на другого (пример, мы хотим в полях персонажа иметь поле «отец»).
Удобно ли это делать через поля или через загрузы.

**Comment by giuliorm** [comment]
Пускай у персонажа будут "Связи". Формат "связи" - поля "с кем" (т.е. ссылка на другого персонажа), может быть, "тип" (родители, любимый человек, неведомая хрень) и "описание"

**Comment by leotsarev** [comment]
Подумаем позже :-) Идеи писать не возбраняется
