### ISSUE TITLE
Проектирование структуры Базы Данных

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#3]
Вот изначальный mind map
http://goo.gl/UzkazX
Как выглядит структура БД в оригинальной allrpg.info тоже могу показать
Поучаствовать выражал желание @aestetique

Сс: @joinrpg/developers

**Comment by leotsarev** [comment]
Обновил вики про сущности https://github.com/joinrpg/joinrpg/wiki/%D0%A1%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8

cc @joinrpg/developers @joinrpg/product

**Comment by leotsarev** [comment]
И переименовал в https://github.com/joinrpg/joinrpg/wiki/Entities
Потому что сил моих нет с нечитаемыми русскими названиями.

**Comment by dair** [comment]
Модель базы, драфт 0.0.0.1
Документ для редактирования в http://draw.io: https://www.draw.io/?#G0B4dXvewrRkwSSDVMd3F0Q3ZlYkU

![joinrpg](https://cloud.githubusercontent.com/assets/1554439/4200040/fd92dc50-380b-11e4-8b8d-49ddcef04ebc.png)

**Comment by dair** [comment]
Меня немного опечалило, что заявка может быть привязана к группе, это для меня ВНЕЗАПНО.
Но смысл мне понятен, но как сделать это хорошо — понимаю не очень, сделал так как сделал — будет две ссылки, одна на ROLE, одна на GROUP, уже на уровне приложения надо убеждаться и гарантировать то, что валидна будет в каждый момент времени только одна, а вторая NULL.

**Comment by leotsarev** [comment]
Предлагаю не закрывать задачи, пока не закончится все (например по этой схеме могут быть обсуждения/замечания/все такое).

А зачем `GROUP_PROP` и `ROLE_PROP` разные таблицы?
Почему `PERSON` называется не `USER` ?
Я бы назвал `MASTER` как-то вроде `PROJECT_RIGHTS` или `USER_PROJECT_ROLES`

**Comment by leotsarev** [comment]
Отвечая на замечание Даира — в принципе можно попробовать вот что сделать — всегда создавать запись в `ROLE` при подаче заявки в ГРУППУ, но делать там типа флага, что ROLE мол неокончательно еще утверждена.

**Comment by dair** [comment]
Я нажал кнопку "close and comment" думая, что оно закроет окно ввода, а не issue. Больше не повторится, сорри.

> А зачем GROUP_PROP и ROLE_PROP разные таблицы?

Вижу так:
Мастер создаёт группу, для неё прописывает предопределённые поля.
Потом создаётся роль в этой группе, ей автоматом присваиваются значения из группы (берем из GROUP_PROP и кладём в ROLE_PROP), в дальнейшем они могут меняться уже там.

> Почему PERSON называется не USER ?

Слово user является зарезервированным в некоторых БД и таблица такая есть.
И ещё, кстати, можно подумать, что юзер один, а вот персон может теоретически быть больше одной — родитель за детей, муж за жену и т.п.

>  Я бы назвал MASTER как-то вроде PROJECT_RIGHTS или USER_PROJECT_ROLES

Согласен с PROJECT_RIGHTS.

**Comment by leotsarev** [comment]
> И ещё, кстати, можно подумать, что юзер один, а вот персон может теоретически быть больше одной — родитель за детей, муж за жену и т.п.

Мы решили, что это non-issue. XXI век на дворе, как никак. Но аргументы принимаются.

> О, миленько. я бы только предложил переименовать ... А role\* в character*

двачую это предложение

**Comment by leotsarev** [comment]
`MASTER` → `PROJECT_RIGHT`
`PERSON` → `USER`
`ROLE` → `CHARACTER`
`CLAIM` stays

**Comment by Murphy812** [comment]
MASTER → PROJECT_ACL

Мне кажется, rights тут это какой-то советский английский, а ACL - общепринятая аббревиатура для обозначения управления доступом (access list). Теоретически мы и для игроков могли бы делать там записи, но по факту сейчас получается, что для игроков там записи просто нет, а для мастеров есть. А на 2м этапе можно в этой же табличке более гибко настраивать права для разных мастеров (например, сейчас просто Вася->Ведьмак, а там будет Вася->Ведьмак->Каэдвен - Вася будет управлять информацией только по группе "Каэдвен" и игрокам, которые с ней связаны).

**Comment by aestetique** [comment]
Я все еще в отпуске и без нормального интернета, но поддерживаю про ACL вместо RIGHTS.

**Comment by leotsarev** [comment]
Даир, а можно прокомментировать вопрос почему выбрана схема хранения в ROLE_PROP а не в JSON ?

**Comment by dair** [comment]
Одно другому не мешает.
Или предлагаешь все свойства строкой-json сразу пихать в персонажа/группу?

**Comment by leotsarev** [comment]
Да. Не сколько предлагаю, сколько спрашиваю.
09 сент. 2014 г. 15:59 пользователь "Vladimir Lebedev-Schmidthof" <
notifications@github.com> написал:

**Comment by aestetique** [comment]
Пожалуйста, объясните, почему не так?

![joinrpg_draft](https://cloud.githubusercontent.com/assets/6359503/4882056/0e9f89d8-6351-11e4-8cea-70adde60eaf7.jpg)

**Comment by dair** [comment]
Если ты глянешь в свежеобновлённую модель, то этот квадрат там тоже есть.

**Comment by aestetique** [comment]
Можно ссылку? Если https://www.draw.io/?#G0B4dXvewrRkwSSDVMd3F0Q3ZlYkU - получаю unknown error на входе, если нужно выдать права на гуглдоки - то на s.o.voronin@gmail.com, пожалуйста

**Comment by dair** [comment]
https://drive.google.com/file/d/0B4dXvewrRkwSSDVMd3F0Q3ZlYkU/view?usp=sharing

Я сначала её неправильно вставил, прошу прощения

![screen shot 2014-11-04 at 14 37 00](https://cloud.githubusercontent.com/assets/1554439/4899007/f16f242e-6416-11e4-9e33-33e81ee449ef.png)

Выбрать "draw.io"

**Comment by leotsarev** [comment]
Есть ли у кого-нибудь дополнительные комменты, или закрываем задачу?
