### ISSUE TITLE
joinrpg-update.sh должен запускать migrate и pip install

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#31]
Настрой пожалуйста скрипт `joinrpg-update.sh` так, чтобы он запускал `migrate` и `pip install -r requirements.txt`, тебе это быстрее немного :-)

Я прикрутил домен http://beta.joinrpg.ru кстати

**Comment by leotsarev** [comment]
Вот кстати опять много чего упало из-за того, что migrate не происходит.

**Comment by dair** [comment]
Сделал. Надо бы их в репу положить, наверно.

**Comment by leotsarev** [comment]
Да, положи пожалуйста.
Но там похоже все не обновилось правильно http://beta.joinrpg.ru/project/discover/
Может опять базу убить?
