### ISSUE TITLE
Транзакции в БД

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#36]
Привет, @joinrpg/developers !

Давайте обсудим вот какой вопрос — транзакционная целостность.
В django есть режим, в котором можно настроить 1 запрос страницы = 1 транзакция и забыть об этом, как о страшном сне.
Легкость привлекает, но я бы сделал транзакции явными.

Вот здесь про это написано.  https://docs.djangoproject.com/en/1.7/topics/db/transactions/ (как раз бы декоратор atomic и использовал бы).

У кого есть, опыт, можете прокомментировать вопрос?

**Comment by dair** [comment]
Транзакции нужны тогда и только тогда, когда более позднее изменение в 
базе в случае ошибки должно отменить более раннее.
Поэтому, вот когда встретим такое, тогда и.

**Comment by leotsarev** [comment]
Кстати, у нас по умолчанию создаются таблицы MyISAM, а не InnoDB, они транзакции не поддерживают, наверное надо поправить.

Даир, ну например простой пример кода, который я написал на выходных.
- Делаем «Создать проект»
- Делаем «Дать права создателю на все»
- Делаем «Создать корневую локацию»

Я бы хотел, что в случае ошибки при создании корневой локации у нас все откатится как было. Иначе мы получим попорченную базу, где нарушен инвариант «у проекта всегда есть корневая локация, которую нельзя удалить».

**Comment by aestetique** [comment]
Считаю, что глобальный autocommit надо отключить и использовать транзакционный режим во всех наших запросах.

++ надо сконвертить все существующие таблицы в InnoDB и новые таблицы создавать в нем же

Всевозможные создания пользователя с первоначальной выдачей прав, создания и редактирования проектов, заведение и правка заявок у нас в любом случае будут задействовать более одной таблицы.

**Comment by leotsarev** [comment]
Про InnoDB — это ведь в любом случае нужно?

Прокомментируй пожалуйста выбор между использования в django режима «Вся обработка 1 HTTP запроса = 1 транзакция» и «Функции, где что-то править, обрамлять декоратором, которые начинает транзакцию».

**Comment by dair** [comment]
Я думаю, что вот этот django-режим хороший, надо его включить. Будет что 
не так — перейти на вариант 2.

**Comment by aestetique** [comment]
Насколько я понял из дока, если не хочется вручную контролировать состояние автокоммита и проставлять везде в нужных местах коммиты самим - лучше использовать предложенный atomic

Savepoints нам для наших задач не нужны

InnoDB я использовал для банка на Темной Стороне - http://dev.dvrpg.ru/insomnia/, во время игры нагрузка на БД была примерно как типичная для существующего allrpg.info, проблем с рассинхронизацией данных в БД не возникало. И да, для транзакций в любом случае нужно, MyISAM их не поддерживает

**Comment by leotsarev** [comment]
«вручную контролировать состояние автокоммита и проставлять везде в нужных местах коммиты самим» — это вариант (3).
1. Использовать ATOMIC_COMMITS = True. Это тоже самое, как если у каждой функции views.py есть декоратор `@atomic`.
2. Использовать декоратор `@atomic` вокруг каждой вьюшки/функции, меняющей состояние базы (т.е. где нам нужно). Где не нужно, не использовать. Плюс — в отсутствии лишних транзакций, если мы делаем только `SELECT`
3. Делать все вручную, типа `begin()` `commit()` и все это.

Я лично за вариант (2), т.к. пусть работы чуть больше, зато понятнее что происходит. (1) вариант еще плох тем, что если мы задумаем перейти от него ко варианту (2), нам придется весь код руками смотреть.

**Comment by dair** [comment]
Тогда ок, я за (2).

**Comment by aestetique** [comment]
++

**Comment by leotsarev** [comment]
Ок. Оставлю висеть немного, вдруг кто-то сможет внести еще 5 центов.
Переход на InnoDB ушел в баг #37

**Comment by leotsarev** [comment]
Добавил https://github.com/joinrpg/joinrpg/commit/4b92bef280790e3bea3287ce5738d84244705e93
