### ISSUE TITLE
Логин уже существующего в БД пользователя

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#4]
**Я как пользователь сайта хотел бы иметь возможность залогиниться на каждой странице сайта.**
- на каждой странице в меню показывается блок залогиненности с указанием текущего логина
- Если пользователь залогинен, блок также позволяет разлогиниться.
- Если мы не залогинены, блок предлагающий ввести логин/email и пароль
- В качестве email принимается любой email привязанный к пользователю.
- Успешный логин приводит нас на ту же страницу
- Страницы, недоступные незалогиненному пользователю, не выводят информации в основном блоке страницы, а выводят предложение залогиниться (необходимо создать тестовые страницы для этой цели, если их нет).
- Неуспешный логин приводит к выводу сообщения об ошибке
- Повторный логин после неуспешности приводит нас на ту страницу, куда мы изначально пытались попасть (не на главную страницу)
- При успешном логине мне запоминает на максимально возможное время
- После разлогина пользователь остается на той же странице.
- Необходимо создать тестового пользователя test1/test1 для тестирования этой фичи
- Не входит в задачу: чекбокс «чужой компьютер/не запоминать меня» #17
- Не входит в задачу: регистрация нового пользователя #5

**Comment by leotsarev** [comment]
Надо ли писать подробнее? Рисовать мокап?
@joinrpg/developers @joinrpg/product

**Comment by leotsarev** [comment]
Макс, будешь ли чего-нибудь делать по таким сторькам, или можно отдавать разработчикам?

**Comment by leotsarev** [comment]
Можно забирать @joinrpg/developers

**Comment by Wildmage** [comment]
Кое что всё-таки забыто. Как насчёт возможности РАЗлогиниться на каждой странице сайта? Куда должен попадать пользователь после разлогина на публичной странице? На закрытой странице?

**Comment by giuliorm** [comment]
так кнопка "Выйти" рядом с именем пользователя. Попадает на главную. Кстати, надо решить, что будет главной страницей, если пользователь не залогинен

**Comment by Wildmage** [comment]
Подожди, не беги впереди паровоза. Мы и для залогиненного пользователя пока не знаем, что будет "главной" страницей. Потому что сценариев нет. Опять же, вопрос о перекидывании на главную при выходе не кажется мне очевидным. Представь себе, например, такой сценарий - боевая команда, собравшись на тренировку, подаёт заявки на всех в одну армию, с одного планшета...

**Comment by leotsarev** [comment]
Добавил про разлогин. 
Предлагаю для простоты оставлять на той же странице, там разберемся.

2Макс. Я не верю в работоспособность процесса с ПОЛНЫМ проектированием всего с самого начала.

**Comment by Wildmage** [comment]
Полное проектирование - явно не наш формат. Но каждый пункт, продуманный заранее - это минус один рефакторинг в будущем, а мы весьма ограничены в ресурсах.

Касательно стартовой страницы - я бы рассмотрел мастерский и игроцкий интерфейсы по разным адресам. Поскольку занимать существенную часть рабочей области табличкой "мои проекты: 0" для 95% пользователей - не самый хороший UX.

**Comment by leotsarev** [comment]
А вот я зашел на главную — и куда попадать при логине? Хитрой эвристикой угадывать, игрок или мастер?
По количеству пользователей все так. А вот по проведенному на сайте времени все далеко не так однозначно, ИМХО.
Уйдет тут в переделку очень мало работы. Не забывай, что за каждой такой сторькой есть немало что сделать в бекенде. 
Ну а потом — разнесем мы готовые блоки по разным страницам, это-то как раз не велика проблема.

**Comment by Wildmage** [comment]
Если ты зашёл на главную со стороны - то у тебя есть список своих заявок, с пометками, где есть обновления, и список актуальных проектов ниже, с кнопочкой "заявиться". Критерий актуальности нужно будет выписать позже - самый простой это количество принятых заявок за последнюю неделю. И возле твоего ника есть маленькая кнопочка "мои проекты", которая ведёт на master.joinrpg.ru. А если у тебя нет ни одного проекта - то кнопочка "создать проект", ведущая туда же.

А вот если ты уже второй месяц фигачишь тысячник, и солнца в окошке не видел две недели, то hot dial твоего браузера сразу ведёт на master.joinrpg.ru

**Comment by Wildmage** [comment]
И идеологическое: Встречают по одёжке. То есть, мы можем выпуститься с багами, с сильно урезанным функционалом, с недоделками. Но одно должно быть понятно с первого взгляда - стало удобнее. Иначе нам не простят )

**Comment by leotsarev** [comment]
Замечание эти мудры сие, хоть и в не теме про стартовую страницу.
Проектирование стартовой страницы игрока ушло в #21 и перекинуто на тебя

**Comment by tsareva** [comment]
Честно говоря, имхо как правило:
Я захожу на аллрпг как мастер с заглавной страницы сайта.
Я захожу на аллрпг как игрок с ссылки уведомления

Во втором случае не принципиально, что часть заглавной страницы занята под
Проекты, которыми я как игрок не пользуюсь.
В первом случае очень бесит, что необходим дополнительный клик. Особенно в
том разрезе, что у самых активных мастеров (по логике заходят чаще всего)
обычно актуальный проект один.

5 сентября 2014 г., 16:57 пользователь Max Gusev notifications@github.com
написал:

**Comment by Wildmage** [comment]
Не в той теме. Продолжение в #21
