### ISSUE TITLE
Распределение задач

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#6]
@joinrpg/developers 

Как будем распределять задачи между разработчиками? Создаются, а потом хватает кто что может?
Даир распределяет? 
Еще как-нибудь?

**Comment by giuliorm** [comment]
Пускай кто-то один распределяет. Будет общий список сразу хотя бы.

**Comment by leotsarev** [comment]
Ну короче пока либо хватать самим, либо ко мне.
