### ISSUE TITLE
 Финализировать список используемых технологий

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#7]
Нужно понимать, какой конкретно мы используем Питон / django и БД.
Хватит ли нам возможностей Щорса http://www.diphost.ru/hosting/

**Comment by giuliorm** [comment]
Python 3.3, потому что требуется для Django по ссылке и является последней версией.

> > All these versions of Python include a lightweight database called SQLite 
> > использовать встроенную, либо MSSQL или Oracle

**Comment by lncubus** [comment]
тогда нужно немного поправить инструкцию по установке, ибо в current убунте по-умолчанию python - это python 2.7.6

**Comment by lncubus** [comment]
Собственно, ничего сложного, для *ubuntu

sudo apt-get install python3-pip
sudo pip3 install Django

Различия между питоном 2 и 3 упоминаются в учебном курсе.
Чего я не нашел, так это ответа на впопрос, какая вверсия стоит у Щорса.

**Comment by lncubus** [comment]
Для тех, кто не любит ставить system-wide есть инструкция по созданию виртуального окружения.
http://ilikepython.blogspot.ru/2013/12/python-3-pyvenv.html

**Comment by leotsarev** [comment]
Пока что все обсуждено и решено. Закрываю.
