### ISSUE TITLE
Условная стартовая страница (список проектов/заявок)

### ISSUE THREAD

**Issue by leotsarev** [joinrpg/joinrpg-unused#8]
Я как пользователь сайта хочу иметь стартовую страницу, котора позволит мне выполнять базовые действия на сайте на текущем прототипе.
- На этой странице пользователь также видит полный список своих заявок и кнопку «заявиться»
- На этой странице пользователь видит полный список своих проектов (с возможностью перейти на «страницу проекта») и кнопку «добавить проект».
- Если я не залогинен, я вижу предложение залогинится 
- Для всех страниц (страница заявки, страница проекта, добавить проект, заявиться) сделать заглушки, если их еще нет

**Comment by Wildmage** [comment]
Сценарии бы написать - тогда уже можно будет думать, какая страница должна быть стартовой.

Сорри, не привык пока к интерфейсу. Закрыл, кажется, случайно. Всё, нашёл как открыть.

**Comment by leotsarev** [comment]
В рамках этой задачи хочу базовый (самый базовый) прототип этой страницы. Дальше решим.

Можно делать @joinrpg/developers
